# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#

name: Sync from tflite-micro

on:
  schedule:
    # 2pm UTC is 7am or 8am PT depending on daylight savings.
    - cron: '0 14 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.repository == 'advaitjain/tflite-micro-sparkfun-edge-examples')

    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - name: Sync the code
        run: |
          ./scripts/sync_from_tflite_micro.sh
          git config --local user.name "advaitjain-bot"
          git config --local user.email "advaitjain-bot@google.com"
          git add *

          if [[ $(git status --porcelain | wc -l) == 0 ]]; then
            echo "no changes"
          else
            git commit -m "Sync from tflite-micro."
          fi

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
        with:
          branch: sync-from-tflite-micro
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
          title: (Sparkfun Edge) Automated sync from github.com/tensorflow/tflite-micro
          commit-message: Automated sync from github.com/tensorflow/tflite-micro
          committer: advaitjain-bot <advaitjain-github-bot@google.com>
          author: advaitjain-bot <advaitjain-github-bot@google.com>
          body: "(Sparkfun Edge) Automated sync from github.com/tensorflow/tflite-micro"
          labels: bot:sync-tf, ci:run
          reviewers: advaitjain
